apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app  #  Match the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80  #  Port the Service exposes within the cluster
      targetPort: 8080  #  Port the container listens on
  type: ClusterIP # Or NodePort, or LoadBalancer
